[build]
  publish = "build/web"
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PWD/flutter/bin:$PATH"
    flutter pub get
    flutter build web --release
  """
